<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Krosoft.Extensions.Testing" Version="2026.8.29.9959" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Krosoft.Extensions.Events.Identity\Krosoft.Extensions.Events.Identity.csproj" />
	</ItemGroup>
</Project>
